[project]
name = "urssi-pixi-demi"
version = "0.1.0"
description = "Add a short description here"
authors = ["frimpsjoek <gy1906@wayne.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
